name: Nick
version: 1.0
author: Streafe
main: me.Streafe.Nick.Nick
description: Nick Plugin by Streafe v 1.0

commands:
  particles:
    usage: /<command>
    description: particles command
  nick:
    usage: /<command>
    description: change your name
    default: false
